name: Add New Member
on:
  pull_request:
    types: [opened]

jobs:
  add_member:
    runs-on: ubuntu-latest

    steps:
      - name: Get Pull Request Author
        id: get_author
        run: |
          PR_AUTHOR="${{ github.actor }}"
          echo "PR_AUTHOR=$PR_AUTHOR" >> $GITHUB_ENV

      - name: Debugging - Print PR Author
        run: echo "PR Author: ${{ env.PR_AUTHOR }}"

      - name: Verify Email from PR
        id: validate_email
        run: |
          EMAIL=$(curl -s -H "Authorization: token ${{ secrets.GITHUBTOKEN_ADDING_PPL }}" \
            "https://raw.githubusercontent.com/${{ github.repository }}/main/students.md" | \
            grep -A 1 "GitHub Username: \[${{ env.PR_AUTHOR }}\]" | grep -oP '(?<=IIIT Delhi Email: \[)[^\]]*')
          echo "Extracted Email: $EMAIL"
          if [[ $EMAIL == *@iiitd.ac.in ]]; then
            echo "email_valid=true" >> $GITHUB_ENV
          else
            echo "email_valid=false" >> $GITHUB_ENV
          fi

      - name: Add Member to Organization
        if: env.email_valid == 'true'
        run: |
          curl -X PUT -H "Authorization: token ${{ secrets.GITHUBTOKEN_ADDING_PPL }}" \
            "https://api.github.com/orgs/${{ github.repository_owner }}/memberships/${{ env.PR_AUTHOR }}" \
            -d '{"role":"member"}'

      - name: Comment on Pull Request
        if: env.email_valid == 'true'
        run: |
          COMMENT="Congratulations! Your email has been verified, and you have been added to the organization."
          PR_URL=$(jq -r '.pull_request.url' $GITHUB_EVENT_PATH)
          curl -X POST -H "Authorization: token ${{ secrets.GITHUBTOKEN_ADDING_PPL }}" -d "{\"body\": \"$COMMENT\"}" $PR_URL/comments

      - name: Comment on Invalid Email
        if: env.email_valid == 'false'
        run: |
          COMMENT="Invalid email address. Please use your IIIT Delhi email (ending with @iiitd.ac.in)."
          PR_URL=$(jq -r '.pull_request.url' $GITHUB_EVENT_PATH)
          curl -X POST -H "Authorization: token ${{ secrets.GITHUBTOKEN_ADDING_PPL }}" -d "{\"body\": \"$COMMENT\"}" $PR_URL/comments